### ISSUE TITLE
Test local (GPFS/HDFS) versus xrootd

### ISSUE THREAD

**Issue by kreczko** [BristolTopGroup/NTupleProduction#123]
Now that we are more familiar with condor, we should try and compare the two modes of operation:
 run ntuple code on DICE with data 
- [x] via xrootd
- ~~[ ] on GPFS (aka local)~~
- [x] on HDFS (aka local 2)
and time it.

**Comment by raggleton** [comment]
A first look at performance with MC via xrootd vs HDFS (local) is here: 

https://github.com/raggleton/condor-comforter/blob/master/cmsRun/XrootdVsLocal/XRootD%20vs%20Local%20profiling.ipynb

This is using a basic CMSSW config file. Not many data points, but so far shows that there are no major differences in run time for xrootd vs local (at least in my config).

**Comment by kreczko** [comment]
Thanks @raggleton
