### ISSUE TITLE
ntp setup links

### ISSUE THREAD

**Issue by DouglasBurns** [BristolTopGroup/NTupleProduction#210]
Currently when running ntp setup links, with some symlinks already active it results in an error.

ln: creating symbolic link `/storage/db0268/TopCrossSections/80X/NTupleProduction/workspace/CMSSW_8_0_8_patch1/src/BristolAnalysis/NTupleTools/BuildFile.xml': File exists

If a symlink does not exist and needs to be remade it is not currently possible. Need to add a condition if a symlink already exists then to skip trying to recreate it.

**Comment by kreczko** [comment]
This should be now fixed. Instead of the error you should see warning messages:
```
ntp setup links
Link /vagrant/workspace/CMSSW_8_0_8_patch1/src/BristolAnalysis/NTupleTools/BuildFile.xml already exists...skipping.
Link /vagrant/workspace/CMSSW_8_0_8_patch1/src/BristolAnalysis/NTupleTools/data already exists...skipping.
Link /vagrant/workspace/CMSSW_8_0_8_patch1/src/BristolAnalysis/NTupleTools/interface already exists...skipping.
Link /vagrant/workspace/CMSSW_8_0_8_patch1/src/BristolAnalysis/NTupleTools/plugins already exists...skipping.
Link /vagrant/workspace/CMSSW_8_0_8_patch1/src/BristolAnalysis/NTupleTools/python already exists...skipping.
Link /vagrant/workspace/CMSSW_8_0_8_patch1/src/BristolAnalysis/NTupleTools/src already exists...skipping.
Link /vagrant/workspace/CMSSW_8_0_8_patch1/src/BristolAnalysis/NTupleTools/test already exists...skipping.
```
