### ISSUE TITLE
Reduce number of stored leptons

### ISSUE THREAD

**Issue by kreczko** [BristolTopGroup/NTupleProduction#274]
In the current ntuples I've seen lepton numbers as high as the 20s.
Most of these additional leptons do not even qualify for our loose lepton selection (low quality or low p<sub>T</sub>).

We should limit the leptons probably to loose/probe leptons or simply put a limit on the size (e.g. [MaxSize=5](https://github.com/BristolTopGroup/NTupleProduction/blob/master/python/BristolNTuple_Muons_cfi.py#L7))

What do you think?

Jet numbers also reach the 20s...

**Comment by DouglasBurns** [comment]
20+ does seem a bit excessive. I think a min pt cut on objects to be stored
would be good (<5 or 10 GeV) And yeah i do not think there is a point in
storing objects that fail even the loosest id either

*________________________*


*Douglas Burns*
*PhD Student*

School of Physics            IIHE
University of Bristol          Vrije Universiteit Brussel
HH Wills Physics Lab      Building G
Tyndall Avenue                Pleinlaan 2
Bristol                              1050 Brussels
BS8 1TL

Douglas.Burns@bristol.ac.uk

**Comment by kreczko** [comment]
For a TTJets sample (`/hdfs/TopQuarkGroup/ec6821/0.0.10/ntuple/v0.0.10/Spring16/TTJets_PowhegPythia8/tmp/ntuple_job_9*/*.root`) I get:
```
MaxElectrons: 9
MaxMuons: 21
Max jets: 22
```
for the muon channel.

If you look at the 1 event with 20 muons (there are not many with so many muons), you can see quickly why we discard them:
```
Muon pT:
[ [56.32326888872959, 25.459270474538414, 20.10230064206555, 15.069183350271837, 11.266513824960306, 10.90675926189081, 9.010873797223562, 8.070458409611676, 7.233413700197627, 6.513597008589129, 5.770774364320555, 5.325683592356902, 5.087347035159007, 4.746724600348174, 4.279348852160899, 4.032979967766878, 3.571192981358373, 1.1879529984088484, 0.8832949373283201, 0.8618557464709106]]
Muon eta
[ [0.29459255930981393, 2.2468018532502447, 2.358687639354677, 2.2169535160023384, 2.1967663764992262, 2.30086374286827, 2.2465858456802534, 2.0198698047859907, 2.346922874013568, 2.2160189156028958, 1.9616016150277211, 1.9876755476073678, 2.353213309541689, -1.192332507373788, 2.431128501344063, 2.2441165439209603, 2.2340075968012707, 1.8471804819951192, 2.3372783685271954, 1.943118451687905]]
```
Every muon except the first one fails either the &eta; cut of 2.1 or is blow 10 GeV in p<sub>T</sub>.
So a cut on pT would be indeed useful as the other muons (|&eta;| > 2.1) might be useful for Tag&Probe.

**Comment by EmyrClement** [comment]
I agree with reducing the number of leptons.  Are the extra jets failing 
cuts as well?  We're now getting the odd event with 15 good jets, so I'd 
rather not reduce the number of (almost good) stored jets.  Also, do 
these limits apply to pseudo objects?

**Comment by kreczko** [comment]
I can have a look, but would also rather not reduce the jets.
The distribution for the event with the highest amount of jets is

```
Jet pT:
[ [478.7780932691821, 360.07394540682, 260.48306846311453, 254.83913218186495, 141.17950197974844, 109.04967898550272, 66.84315265928363, 60.773935684139836, 57.54985732340848, 53.78884572145985, 53.15728709557828, 49.442273684969905, 40.37021832518502, 35.84270454369901, 34.67467508703045, 29.12375271461558, 28.998616493548113, 28.577202149521934, 26.624954422134824, 20.87411731427482, 20.362728321665628, 19.496808546677546]]
Jet Eta
[ [-0.20706030726982355, -1.3473917245996296, -2.286882637602917, -1.2298619735036398, -1.5436333402293312, -1.7471412418790688, -0.42630064497424813, 0.6229580042029961, 3.83516240100578, -0.274353086842388, 0.9884604219887663, -0.06612903628284582, -0.347151875536161, -0.8856741190627447, 0.4925099909293823, -2.7901911743039203, -0.9230967765969923, 1.0020599370571992, -0.6812301879431767, -3.7115955341142577, -2.668322324622564, -2.155967950928397]]
```

All 21 Jets are either above or very close to our 20 GeV cut. Only a few of the jets are at high &eta;, but only 2 of them are what I would classify as forward jets. I think that's fine.
